services:
  - type: web
    name: barkley-lms
    env: docker
    plan: standard
    region: ohio
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: barkley-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: barkley-cache
          property: connectionString

  - type: redis
    name: barkley-cache
    plan: starter
    region: ohio
    ipAllowList: []

databases:
  - name: barkley-db
    plan: standard
    region: ohio
    databaseName: barkley_production
    user: barkley