services:
  - type: web
    name: barkley-lms
    env: docker
    region: ohio
    plan: standard
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: barkley-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: barkley-cache
          type: redis
          property: connectionString

  - type: redis
    name: barkley-cache
    region: ohio
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  - name: barkley-db
    region: ohio
    plan: starter
    databaseName: barkley_production
    user: barkley_user